name: CI test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      actions: read
      checks: write
      id-token: write
    name: Build & Test

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle for a non-wrapper project
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Build lib
        run: gradle assemble

      - name: Run tests
        run: gradle test --info

      - name: Publish
        run: gradle publish

      - name: Generate API documentation
        run: gradle dokkaHtml

      - name: Deploy API documentation to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/docs
