name: CI test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build & Test

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: 22
      - name: Setup Gradle for a non-wrapper project
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Build lib
        run: gradle assemble

      - name: Run tests
        run: gradle test --info
