name: CI test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build & Test

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 22

      - name: Build lib
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew test --info
