name: Release pipeline

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: 22

      - name: Build lib
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew test --info

  publish:
    needs: [ test ]
    name: Build and publish library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: 22

      - name: Build lib
        run: ./gradlew assemble --info

      - name: Publish to Maven Central
        run: ./gradlew publish

      - name: Generate API documentation
        run: ./gradlew dokkaHtml

      - name: Deploy API documentation to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/docs
